=== haramkhor2011-ship-it/claims-app/src/main/resources/xsd/RemittanceAdvice.xsd
<xs:schema xmlns:tns="http://www.eclaimlink.ae/DHD/ValidationSchema" elementFormDefault="qualified" version="2.0" id="RemittanceAdvice" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import schemaLocation="CommonTypes.xsd" namespace="http://www.eclaimlink.ae/DHD/ValidationSchema" />
    <xs:element name="Remittance.Advice">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" name="Header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" name="SenderID" type="tns:HeaderSenderID" />
                            <xs:element minOccurs="1" maxOccurs="1" name="ReceiverID" type="tns:HeaderReceiverID" />
                            <xs:element minOccurs="1" maxOccurs="1" name="TransactionDate" type="tns:HeaderTransactionDate" />
                            <xs:element minOccurs="1" maxOccurs="1" name="RecordCount" type="tns:HeaderRecordCount" />
                            <xs:element minOccurs="1" maxOccurs="1" name="DispositionFlag" type="tns:HeaderDispositionFlag" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="Claim">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" name="ID" type="tns:ClaimID" />
                            <xs:element minOccurs="1" maxOccurs="1" name="IDPayer" type="tns:ClaimIDPayer" />
                            <xs:element minOccurs="0" maxOccurs="1" name="ProviderID" type="tns:ClaimProviderID" />
                            <xs:element minOccurs="0" maxOccurs="1" name="DenialCode" type="tns:ClaimDenialCode" />
                            <xs:element minOccurs="1" maxOccurs="1" name="PaymentReference" type="tns:ClaimPaymentReference" />
                            <xs:element minOccurs="0" maxOccurs="1" name="DateSettlement" type="tns:ClaimDateSettlement" />
                            <xs:element minOccurs="0" maxOccurs="1" name="Encounter">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="1" name="FacilityID" type="tns:EncounterFacilityID" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element minOccurs="1" maxOccurs="unbounded" name="Activity">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="1" maxOccurs="1" name="ID" type="tns:ActivityID" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Start" type="tns:ActivityStart" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Type" type="tns:ActivityType" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Code" type="tns:ActivityCode" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Quantity" type="tns:ActivityQuantity" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Net" type="tns:ActivityNet" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="List" type="tns:ActivityList" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Clinician" type="tns:ActivityClinician" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="PriorAuthorizationID" type="tns:ActivityPriorAuthorizationID" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="Gross" type="tns:ActivityGross" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="PatientShare" type="tns:ActivityPatientShare" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="PaymentAmount" type="tns:ActivityPaymentAmount" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="DenialCode" type="tns:ActivityDenialCode" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== haramkhor2011-ship-it/claims-app/data/ready/CNMD925253889_80638543_1_1_DHA-F-0045446.xml
<?xml version="1.0" encoding="utf-8"?>
<Remittance.Advice xmlns:tns="http://www.eclaimlink.ae/DHD/ValidationSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.eclaimlink.ae/DHD/ValidationSchema/RemittanceAdvice.xsd">
  <Header>
    <SenderID>INS012</SenderID>
    <ReceiverID>DHA-F-0045446</ReceiverID>
    <TransactionDate>03/09/2025 11:54</TransactionDate>
    <RecordCount>1</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>DLJOI1021613882</ID>
    <IDPayer>68011615</IDPayer>
    <ProviderID>DHA-F-0045446</ProviderID>
    <PaymentReference>80638543</PaymentReference>
    <DateSettlement>01/09/2025 00:00</DateSettlement>
    <Comments>Activity ID: 300141 - AUTH-003</Comments>
    <Encounter>
      <FacilityID>DHA-F-0045446</FacilityID>
    </Encounter>
    <Activity>
      <ID>300142</ID>
      <Start>13/06/2025 05:03</Start>
      <Type>8</Type>
      <Code>10</Code>
      <Quantity>1</Quantity>
      <Net>144</Net>
      <Clinician>DHA-P-0128573</Clinician>
      <Gross>180</Gross>
      <PatientShare>36</PatientShare>
      <PaymentAmount>144</PaymentAmount>
    </Activity>
  </Claim>
</Remittance.Advice>

=== haramkhor2011-ship-it/claims-app/data/ready/RA_GC03_PHUB528147892_02092025221518_NAS_To_DHA-F-0045446.xml
<?xml version="1.0" encoding="utf-8"?>
<Remittance.Advice xmlns:tns="http://www.eclaimlink.ae/DHD/ValidationSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.eclaimlink.ae/DHD/ValidationSchema/RemittanceAdvice.xsd">
  <Header>
    <SenderID>TPA004</SenderID>
    <ReceiverID>DHA-F-0045446</ReceiverID>
    <TransactionDate>02/09/2025 22:15</TransactionDate>
    <RecordCount>1</RecordCount>
    <DispositionFlag>PRODUCTION</DispositionFlag>
  </Header>
  <Claim>
    <ID>DLJOI1021613219</ID>
    <IDPayer>8865317-34</IDPayer>
    <ProviderID>DHA-F-0045446</ProviderID>
    <PaymentReference>GC03_PHUB528147892</PaymentReference>
    <DateSettlement>02/09/2025 22:15</DateSettlement>
    <Comments>
    </Comments>
    <Encounter>
      <FacilityID>DHA-F-0045446</FacilityID>
    </Encounter>
    <Activity>
      <ID>200113031</ID>
      <Start>09/06/2025 20:11</Start>
      <Type>3</Type>
      <Code>85025</Code>
      <Quantity>1</Quantity>
      <Net>111.72</Net>
      <List>111.72</List>
      <Clinician>DHA-P-30387015</Clinician>
      <PatientShare>0</PatientShare>
      <PaymentAmount>0</PaymentAmount>
      <DenialCode>MNEC-005</DenialCode>
    </Activity>
    <Activity>
      <ID>200114091</ID>
      <Start>09/06/2025 20:11</Start>
      <Type>3</Type>
      <Code>86140</Code>
      <Quantity>1</Quantity>
      <Net>111.72</Net>
      <List>111.72</List>
      <Clinician>DHA-P-30387015</Clinician>
      <PatientShare>0</PatientShare>
      <PaymentAmount>0</PaymentAmount>
      <DenialCode>MNEC-005</DenialCode>
    </Activity>
    <Activity>
      <ID>300162571</ID>
      <Start>09/06/2025 20:11</Start>
      <Type>3</Type>
      <Code>96365</Code>
      <Quantity>1</Quantity>
      <Net>96.04</Net>
      <List>96.04</List>
      <Clinician>DHA-P-30387015</Clinician>
      <Gross>96.04</Gross>
      <PatientShare>0</PatientShare>
      <PaymentAmount>96.04</PaymentAmount>
    </Activity>
  </Claim>
</Remittance.Advice>

=== haramkhor2011-ship-it/claims-app/target/classes/xml/remit_min_ok.xml
<Remittance.Advice xsi:noNamespaceSchemaLocation="RemittanceAdvice.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Header>
        <SenderID>TPA-XYZ</SenderID><ReceiverID>FAC-001</ReceiverID>
        <TransactionDate>24/02/2025 22:41</TransactionDate>
        <RecordCount>1</RecordCount><DispositionFlag>PRODUCTION</DispositionFlag>
    </Header>
    <Claim>
        <ID>R-OK-1</ID>
        <IDPayer>PAY-1</IDPayer>
        <ProviderID>FAC-001</ProviderID>
        <PaymentReference>PR-001</PaymentReference>
        <DateSettlement>21/02/2025 00:00</DateSettlement>
        <Encounter><FacilityID>FAC-001</FacilityID></Encounter>
        <Activity>
            <ID>RA1</ID><Start>21/02/2025 00:00</Start><Type>3</Type><Code>85025</Code>
            <Quantity>1</Quantity><Net>111.72</Net><Clinician>DHA-P-0001</Clinician>
            <PaymentAmount>111.72</PaymentAmount>
        </Activity>
    </Claim>
</Remittance.Advice>

=== haramkhor2011-ship-it/claims-app/data/ready/DHA-F-0045446-29538860-24592649-03092025111244.XML
<Remittance.Advice xmlns:tns="http://www.eclaimlink.ae/DataDictionary/CommonTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.eclaimlink.ae/DataDictionary/CommonTypes/RemittanceAdvice.xsd"><Header><SenderID>TPA002</SenderID><ReceiverID>DHA-F-0045446</ReceiverID><TransactionDate>03/09/2025 11:12</TransactionDate><RecordCount>1</RecordCount><DispositionFlag>PRODUCTION</DispositionFlag></Header><Claim><ID>DLJOI1021616259</ID><IDPayer>24317607-112-2</IDPayer><ProviderID>DHA-F-0045446</ProviderID><PaymentReference>2621190</PaymentReference><DateSettlement>02/09/2025 00:00</DateSettlement><Comments></Comments><Encounter><FacilityID>DHA-F-0045446</FacilityID></Encounter><Activity><ID>300164121</ID><Start>25/06/2025 12:24</Start><Type>3</Type><Code>99195</Code><Quantity>1</Quantity><Net>263.69</Net><Clinician>DHA-P-0250490</Clinician><PaymentAmount>263.69</PaymentAmount></Activity><Activity><ID>300162641</ID><Start>25/06/2025 12:24</Start><Type>3</Type><Code>96372</Code><Quantity>1</Quantity><Net>31.21</Net><Clinician>DHA-P-0250490</Clinician><PaymentAmount>31.21</PaymentAmount></Activity><Activity><ID>300121</ID><Start>25/06/2025 12:24</Start><Type>8</Type><Code>9.01</Code><Quantity>1</Quantity><Net>0</Net><Clinician>DHA-P-0250490</Clinician><PaymentAmount>0</PaymentAmount></Activity><Activity><ID>3001137961</ID><Start>25/06/2025 12:24</Start><Type>5</Type><Code>0717-378503-1021</Code><Quantity>3</Quantity><Net>19.2</Net><Clinician>DHA-P-0250490</Clinician><PaymentAmount>19.2</PaymentAmount></Activity><Activity><ID>200113031</ID><Start>25/06/2025 12:24</Start><Type>3</Type><Code>85025</Code><Quantity>1</Quantity><Net>92.64</Net><Clinician>DHA-P-0250490</Clinician><PaymentAmount>92.64</PaymentAmount></Activity></Claim></Remittance.Advice>

=== haramkhor2011-ship-it/claims-app/src/main/resources/xml/remit_multi_acts_ok.xml
<Remittance.Advice xsi:noNamespaceSchemaLocation="RemittanceAdvice.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Header>
        <SenderID>TPA-XYZ</SenderID><ReceiverID>FAC-001</ReceiverID>
        <TransactionDate>24/02/2025 22:41</TransactionDate>
        <RecordCount>1</RecordCount><DispositionFlag>PRODUCTION</DispositionFlag>
    </Header>
    <Claim>
        <ID>R-MULTI-1</ID>
        <IDPayer>PAY-1</IDPayer>
        <ProviderID>FAC-001</ProviderID>
        <PaymentReference>PR-003</PaymentReference>
        <DateSettlement>21/02/2025 00:00</DateSettlement>
        <Activity>
            <ID>RA-1</ID><Start>21/02/2025 00:00</Start><Type>3</Type><Code>85025</Code>
            <Quantity>1</Quantity><Net>111.72</Net><Clinician>DHA-P-0001</Clinician>
            <Gross>111.72</Gross><PatientShare>0</PatientShare><PaymentAmount>111.72</PaymentAmount>
        </Activity>
        <Activity>
            <ID>RA-2</ID><Start>21/02/2025 00:00</Start><Type>3</Type><Code>86141</Code>
            <Quantity>1</Quantity><Net>108.19</Net><Clinician>DHA-P-0001</Clinician>
            <List>108.19</List><PaymentAmount>108.19</PaymentAmount>
        </Activity>
    </Claim>
</Remittance.Advice>
